/**
 * This file was generated by the Jeddict
 */
package com.udea.entity;

import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author Usser
 */
@Entity
public class Cliente {

    @Override
    public String toString() {
        return "Cliente{" + "cedula=" + cedula + ", apellidos=" + apellidos + ", nombres=" + nombres + ", venta=" + venta + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 43 * hash + this.cedula;
        hash = 43 * hash + Objects.hashCode(this.apellidos);
        hash = 43 * hash + Objects.hashCode(this.nombres);
        hash = 43 * hash + Objects.hashCode(this.venta);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (this.cedula != other.cedula) {
            return false;
        }
        if (!Objects.equals(this.apellidos, other.apellidos)) {
            return false;
        }
        if (!Objects.equals(this.nombres, other.nombres)) {
            return false;
        }
        if (!Objects.equals(this.venta, other.venta)) {
            return false;
        }
        return true;
    }

    @Column(nullable = false)
    @Id
    private int cedula;

    @Column(nullable = false)
    @Basic
    private String apellidos;

    @Column(nullable = false)
    @Basic
    private String nombres;

    @OneToOne(targetEntity = Venta.class, mappedBy = "cliente")
    private Venta venta;

    public int getCedula() {
        return this.cedula;
    }

    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

}