//
// This file was generated by the Jeddict
//
package com.udea.entity;

import java.io.Serializable;

public class FotoPK implements Serializable {

    private int id;

    private int mascota;

    public FotoPK() {
    }

    public FotoPK(int id, int mascota) {
        this.id = id;
        this.mascota = mascota;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMascota() {
        return this.mascota;
    }

    public void setMascota(int mascota) {
        this.mascota = mascota;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final FotoPK other = (FotoPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMascota(), other.getMascota())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + this.getId();
        hash = 89 * hash + (this.getMascota() != null ? this.getMascota().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "FotoPK{" + " id=" + id + ", mascota=" + mascota + '}';
    }

}