//
// This file was generated by the Jeddict
//
package com.udea.entity;

import java.io.Serializable;

public class VentaPK implements Serializable {

    private int id;

    private int mascota;

    private int cliente;

    public VentaPK() {
    }

    public VentaPK(int id, int mascota, int cliente) {
        this.id = id;
        this.mascota = mascota;
        this.cliente = cliente;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMascota() {
        return this.mascota;
    }

    public void setMascota(int mascota) {
        this.mascota = mascota;
    }

    public int getCliente() {
        return this.cliente;
    }

    public void setCliente(int cliente) {
        this.cliente = cliente;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final VentaPK other = (VentaPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMascota(), other.getMascota())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getCliente(), other.getCliente())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 19 * hash + this.getId();
        hash = 19 * hash + (this.getMascota() != null ? this.getMascota().hashCode() : 0);
        hash = 19 * hash + (this.getCliente() != null ? this.getCliente().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "VentaPK{" + " id=" + id + ", mascota=" + mascota + ", cliente=" + cliente + '}';
    }

}